development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: demo_dev

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: demo_production
