version: "3.8"

services:
  db:
    image: postgres:12
    container_name: demo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:5.0
    container_name: demo_redis
    command: redis-server
    volumes:
      - ./tmp/redis:/var/lib/redis/data

  web:
    build: .
    container_name: demo_api
    command: bash -c "rm -f tmp/pids/server.pid && /usr/bin/supervisord -n"
    env_file: .env
    ports:
      - "4000:3000"
    volumes:
      - .:/api
    depends_on:
      - db
      - redis

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger.yaml

volumes:
  swagger:
