openapi: 3.0.2
info:
  description: Sample Rails app
  version: 1.0.0
  title: Demo API
servers:
  - url: http://localhost:4000
tags:
  - name: user
    description: Operations about unauthenticated user
  - name: "v1/user"
    description: Operations about authenticated user
  - name: "v1/project"
    description: Operations about a user's project
  - name: "v1/task"
    description: Operations about a user's task
  - name: "admin/project"
    description: Operations about project management
  - name: "admin/task"
    description: Operations about task management
  - name: "admin/user"
    description: Operations about user management

paths:
  /signup:
    post:
      tags:
        - user
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      description: email
                      type: string
                    password:
                      description: password
                      type: string
                    password_confirmation:
                      description: password_confirmation
                      type: string
      responses:
        "201":
          description: OK
          headers:
            Authorization:
              description: Authorization token
              type: string
        "422":
          description: Unprocessable Entity
  /login:
    post:
      tags:
        - user
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      description: email
                      type: string
                    password:
                      description: password
                      type: string
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: Authorization token
              type: string
        "401":
          description: Unprocessable Entity
  /logout:
    delete:
      tags:
        - user
      summary: Logout user
      responses:
        "200":
          description: OK

  /users/show:
    get:
      tags:
        - "v1/user"
      summary: Returns a user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
  /users/update:
    patch:
      tags:
        - "v1/user"
      summary: Updates a user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                avatar:
                  type: file
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /users/update_password:
    patch:
      tags:
        - "v1/user"
      summary: Updates a user's password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []

  /projects:
    get:
      tags:
        - "v1/project"
      summary: Returns a list of projects
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      security:
        - bearerAuth: []
    post:
      tags:
        - "v1/project"
      summary: Creates a new project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /projects/{projectId}:
    get:
      tags:
        - "v1/project"
      summary: Finds a project by ID
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    patch:
      tags:
        - "v1/project"
      summary: Updates a project
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "v1/project"
      summary: Deletes a project
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

  /projects/{projectId}/tasks/:
    get:
      tags:
        - "v1/task"
      summary: Returns a list of tasks
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                  meta:
                    type: array
                    items:
                      type: object
      security:
        - bearerAuth: []
    post:
      tags:
        - "v1/task"
      summary: Creates a new task
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /tasks/{taskId}:
    get:
      tags:
        - "v1/task"
      summary: Finds a task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  summary:
                    type: string
                  description:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    patch:
      tags:
        - "v1/task"
      summary: Updates a task
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "v1/task"
      summary: Deletes a task
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

  /admin/projects:
    get:
      tags:
        - "admin/project"
      summary: Returns a list of projects
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                  meta:
                    type: array
                    items:
                      type: object
      security:
        - bearerAuth: []
  /admin/projects/{projectId}:
    get:
      tags:
        - "admin/project"
      summary: Finds a project by ID
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    patch:
      tags:
        - "admin/project"
      summary: Updates a project
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "admin/project"
      summary: Deletes a project
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

  /admin/projects/{projectId}/tasks/:
    get:
      tags:
        - "admin/task"
      summary: Returns a list of tasks
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                  meta:
                    type: array
                    items:
                      type: object
      security:
        - bearerAuth: []
    post:
      tags:
        - "admin/task"
      summary: Creates a new task
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /admin/tasks/{taskId}:
    get:
      tags:
        - "admin/task"
      summary: Finds a task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  summary:
                    type: string
                  description:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    patch:
      tags:
        - "admin/task"
      summary: Updates a task
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "admin/task"
      summary: Deletes a task
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

  /admin/users:
    get:
      tags:
        - "admin/user"
      summary: Returns a list of users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                  meta:
                    type: array
                    items:
                      type: object
      security:
        - bearerAuth: []
    post:
      tags:
        - "admin/user"
      summary: Creates a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                password:
                  type: string
                role:
                  $ref: "#/components/schemas/Role"
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /admin/users/{userId}:
    get:
      tags:
        - "admin/user"
      summary: Finds a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  role:
                    $ref: "#/components/schemas/Role"
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    patch:
      tags:
        - "admin/user"
      summary: Updates a user
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                password:
                  type: string
                role:
                  $ref: "#/components/schemas/Role"
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "admin/user"
      summary: Deletes a user
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

components:
  schemas:
    Role:
      type: string
      enum:
        - client
        - staff
        - admin

  securitySchemes:
    bearerAuth:
      description: authorization token
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
