openapi: 3.0.2
info:
  description: Sample Rails app
  version: 1.0.0
  title: Demo API
servers:
  - url: http://localhost:4000
tags:
  - name: user
    description: Operations about user
  - name: "v1/project"
    description: Operations about a user's project
  - name: "v1/task"
    description: Operations about a user's task

paths:
  /signup:
    post:
      tags:
        - user
      summary: Register user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      description: email
                      type: string
                    password:
                      description: password
                      type: string
                    password_confirmation:
                      description: password_confirmation
                      type: string
      responses:
        "201":
          description: OK
          headers:
            Authorization:
              description: Authorization token
              type: string
        "422":
          description: Unprocessable Entity
  /login:
    post:
      tags:
        - user
      summary: Login user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      description: email
                      type: string
                    password:
                      description: password
                      type: string
      responses:
        "200":
          description: OK
          headers:
            Authorization:
              description: Authorization token
              type: string
        "401":
          description: Unprocessable Entity
  /logout:
    delete:
      tags:
        - user
      summary: Logout user
      responses:
        "200":
          description: OK

  /projects:
    get:
      tags:
        - "v1/project"
      summary: Returns a list of projects
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                  meta:
                    type: array
                    items:
                      type: object
      security:
        - bearerAuth: []
    post:
      tags:
        - "v1/project"
      summary: Creates a new project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /projects/{projectId}:
    get:
      tags:
        - "v1/project"
      summary: Finds a project by ID
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    put:
      tags:
        - "v1/project"
      summary: Updates a project
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "v1/project"
      summary: Deletes a project
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

  /projects/{projectId}/tasks/:
    get:
      tags:
        - "v1/task"
      summary: Returns a list of tasks
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                  meta:
                    type: array
                    items:
                      type: object
      security:
        - bearerAuth: []
    post:
      tags:
        - "v1/task"
      summary: Creates a new task
      parameters:
        - name: projectId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
  /tasks/{taskId}:
    get:
      tags:
        - "v1/task"
      summary: Finds a task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  summary:
                    type: string
                  description:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
    put:
      tags:
        - "v1/task"
      summary: Updates a task
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
      security:
        - bearerAuth: []
    delete:
      tags:
        - "v1/task"
      summary: Deletes a task
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      description: authorization token
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
